services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: cinema_secretpassword
      POSTGRES_DB:       cinema
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    # environment:
    #   # override or set DATABASE_URL if it’s not picked up from .env:
    #   DATABASE_URL: "postgresql+asyncpg://postgres:cinema_secretpassword@db:5432/cinema"
    volumes:
      - ./backend/vault.db:/app/vault.db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        VITE_MOVIE_URL: ${VITE_MOVIE_URL}
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  db-data: