services:
  api:
    build: ./backend
    image: cinema-api:prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vault.db:/app/vault.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        # forward the env var into the build
        # REACT_APP_MOVIE_URL: ${REACT_APP_MOVIE_URL}
        VITE_MOVIE_URL: ${VITE_MOVIE_URL}
    image: cinema-frontend:prod
    ports:
      - "3000:80"
    depends_on:
      - api
    # # make sure Docker picks up your .env
    # env_file:
    #   - ./.env