services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vault.db:/app/vault.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
